title: "HR App Deployment"
description: "Terraform Script to deploy a HR App to OCI"
informationalText: "Click on the blue button to access the app"
schemaVersion: 1.1.0
version: "20220210"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
    - compartment_ocid
    - tenancy_ocid
    - region

- title: Network Configuration
  visible: true
  variables:
    - generic_vcn_cidr_blocks
    - public_subnet

- title: Compute Configuration
  visible: true
  variables:
    - instance_shape
    - shape_ocpus
    - shape_mems
    - image_os_id
    - ssh_public_key
    - display_name

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment OCID" 
    description: "Please select the target compartment"

  tenancy_ocid:
    type: oci:identity:tenancy:id
    required: true
    title: "Tenancy OCID"
    description: "Please select the target tenancy"

  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Please select the target region"

  generic_vcn_cidr_blocks:
    type: oci:core:vcn:id
    required: true
    title: "Generic VCN CIDR Block"
    description: "Please input the Generic VCN CIDR Block"
    dependsOn:      
       compartmentId: ${compartment_ocid}

  public_subnet:
    type: oci:core:subnet:id
    required: true
    title: "Public Subnet"
    description: "Public Subnet for webapp"
    dependsOn:      
       compartmentId: ${compartment_ocid}
       vcnId: ${generic_vcn_cidr_blocks}

  ssh_public_key:
    title: "SSH Public Key"
    type: oci:core:ssh:publickey
    description: "The public SSH key for the key-pair that you want to use, if you wish to login to the instances over SSH"
    required: true

  instance_shape:
    title: "Instance shape"
    required: true
    type: oci:core:instanceshape:name
    description: "Please choose the supported instance shape"
    dependsOn:      
       compartmentId: ${compartment_ocid}

  shape_ocpus:
    title: "Number of OCPUs of each node"
    required: true
    type: string
    description: "Please key in the number of OCPUs"

  shape_mems:
    title: "Memory of each node in GB"
    required: true
    type: string
    description: "Please key in the amount of memory in GB"

  image_os_id:
    title: "OS Image OCID of the node pool"
    required: true
    visible: false
    type: string
    description: "Please choose the supported OS image for the node"

  display_name:
    title: "Instance display name"
    required: true
    visible: true
    type: string
    description: "Instance display name"

outputs:
  webapp_url:
    type: string
    title: "URL to access webapp"
    displayText: "Webbapp URL"
    visible: true

primaryOutputButton: ${webapp_url}